# Save your player data:
mysql:
  host: 'localhost'
  port: 3306
  database: 'minecraft'
  username: 'username'
  password: ''

# Supports any placeholders from PlaceholderAPI
chat-format: '&d[%channel%] &c%player_name%&7: &f%message%'

# Certain messages have placeholders (%channel%, %word%, %words%)
messages:
  # Success messages:
  success:
    chat-swap: '&7You have switched your chat to &a%channel%&7!'
    filter-add: '&a%word% &7has been added to the filter!'
    filter-remove: '&a%word% &7 has been removed from the filter!'
    filter-list: '&7Words: &a%words%'
  # Usage messages (for commands):
  usage:
    chat-command:
      - 'Chat commands:'
      - '/chat [channel] - switches the channel'
    filter-command: '&c/filter'
    filter-add: '&c/filter add [word]'
    filter-remove: '&c/filter remove [word]'
    filter-list: '&c/filter list'
  # Error messages:
  invalid:
    permission: '&cYou do not have permission to perform this command.'
    sender: '&cYou must be a player to perform this command.'
  # Admin messages:
  admin:
    reloaded: '&aTieredChat has been reloaded!'