# Save your player data:
mysql:
  host: 'localhost'
  port: 3306
  database: 'minecraft'
  username: 'root'
  password: ''

# Supports any placeholders from PlaceholderAPI
# Default: %channel%, %player%, %message%
chat-format: '&d[%channel%] &c%player%&7: &f%message%'

# Certain messages have placeholders (%channel%, %word%, %words%)
messages:
  # Success messages:
  success:
    chat-swap: '&7You have switched your chat to &a%channel%&7!'
    filter-add: '&a%word% &7has been added to the filter!'
    filter-remove: '&a%word% &7has been removed from the filter!'
    filter-list: '&7Words: &a%words%'
  # Failure messages:
  failure:
    already-added: '&c%word% is already in your filter.'
  # Usage messages (for commands):
  usage:
    chat-command:
      - '&7Chat commands:'
      - '&a/chat [channel] &7- switches the channel'
      - '&a/filter &7- block messages from showing up'
    filter-command:
      - '&7Filter commands:'
      - '&a/filter add [word] &7- add a word to your filter'
      - '&a/filter remove [word] &7- remove a word from your filter'
      - '&a/filter list &7- display the words in your filter'
    filter-add: '&7Usage: &a/filter add [word]'
    filter-remove: '&7Usage: &a/filter remove [word]'
    filter-list: '&7Usage: &a/filter list'
  # Error messages:
  invalid:
    permission: '&cYou do not have permission to perform this command.'
    sender: '&cYou must be a player to perform this command.'
    word: '&c%word% is not in your filter.'
  # Admin messages:
  admin:
    reloaded: '&aTieredChat has been reloaded!'